artifact_uri: file:///C:/Users/jra1029/week-3-intro-to-marl-julialruiter/submission/mlflow/826697510224621993/082ab65c53f848f8aeef88bea9ebc8f7/artifacts
end_time: null
entry_point_name: ''
experiment_id: '826697510224621993'
lifecycle_stage: active
run_id: 082ab65c53f848f8aeef88bea9ebc8f7
run_name: CentralizedCritic_MultiGrid-CompetativeRedBlueDoor-v3-CTDE-Red_3b341_00000
run_uuid: 082ab65c53f848f8aeef88bea9ebc8f7
source_name: ''
source_type: 4
source_version: ''
start_time: 1695834833504
status: 1
tags: []
user_id: unknown
