artifact_location: file:///C:/Users/jra1029/week-3-intro-to-marl-julialruiter/submission/mlflow/0
creation_time: 1695827046246
experiment_id: '0'
last_update_time: 1695827046246
lifecycle_stage: active
name: Default
