artifact_uri: file:///C:/Users/jra1029/week-3-intro-to-marl-julialruiter/submission/mlflow/826697510224621993/1b72e150eb8a4dec8ea19f89bd875264/artifacts
end_time: null
entry_point_name: ''
experiment_id: '826697510224621993'
lifecycle_stage: active
run_id: 1b72e150eb8a4dec8ea19f89bd875264
run_name: CentralizedCritic_MultiGrid-CompetativeRedBlueDoor-v3-CTDE-Red_5cb7e_00000
run_uuid: 1b72e150eb8a4dec8ea19f89bd875264
source_name: ''
source_type: 4
source_version: ''
start_time: 1695835748593
status: 1
tags: []
user_id: unknown
